/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyTestProg;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    
    @Test 
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testEculidSubstractionIterative(){
        assertEquals(20, GCD.eculidSubstractionIterative(100,60));
    }

    @Test
    public void testEuclidSubstractionRecursive() {
        assertEquals(20, GCD.euclidSubstractionRecursive(100,60));
    }

    @Test
    public void testEculidDivisionRestIterative() {
        assertEquals(20, GCD.eculidDivisionRestIterative(100,60));
    }

    @Test
    public void testEculidDivisionRestRecursive(){
        assertEquals(20, GCD.eculidDivisionRestRecursive(100,60));
    }

    @Test
    public void testSiebDesEratosthenes(){
        assertEquals("[2, 3, 5, 7, 11]", SDE.siebDesEratosthenes(11));
    }
}
