/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ha3;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) {
        // initialize Stack
    }
}
