/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyTestProg;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Console c = new Console();
        c.setIntegers();
        c.setStrings();
    }
}
